apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam
    stack: demo
  name: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
      version: v1
  template:
    metadata:
      labels:
        app: iam
        stack: demo
        version: v1
    spec:
      containers:
      - image: eu.gcr.io/pmoncada-001/istio-poc/iam:latest
        name: iam
        resources: {}
status: {}
