

steps:

  - id: api
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      IMAGE=api
      docker build -t eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA $$IMAGE/ -f $$IMAGE/Dockerfile
      docker push eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA
    waitFor: ['-']

  - id: audit
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      IMAGE=api
      docker build -t eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA $$IMAGE/ -f $$IMAGE/Dockerfile
      docker push eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA
    waitFor: ['-']

  - id: coverage
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      IMAGE=api
      docker build -t eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA $$IMAGE/ -f $$IMAGE/Dockerfile
      docker push eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA
    waitFor: ['-']

  - id: iam
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      IMAGE=api
      docker build -t eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA $$IMAGE/ -f $$IMAGE/Dockerfile
      docker push eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA
    waitFor: ['-']

  - id: mailer
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      IMAGE=api
      docker build -t eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA $$IMAGE/ -f $$IMAGE/Dockerfile
      docker push eu.gcr.io/pmoncada-001/istio-poc/$$IMAGE:$COMMIT_SHA
    waitFor: ['-']


  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      kubectl apply -f k8s/api
      kubectl apply -f k8s/audit
      kubectl apply -f k8s/coverage
      kubectl apply -f k8s/iam
      kubectl apply -f k8s/mailer
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
    - 'CLOUDSDK_CONTAINER_CLUSTER=keepcoding-2'