apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: csd
spec:
  ports:
  - name: tcp-csd-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
status:
  loadBalancer: {}
